### PR TITLE
Bump ordered-multimap

### PR DESCRIPTION
**Pull request by jplatte**
And also remove `extern crate ini;` from the example :slightly_smiling_face:

### CODE REVIEW

**Comment by marioortizmanero** [comment]
Is dependabot not integrated here? It could be helpful

**Comment by jplatte** [comment]
dependabot doesn't seem to be used that much in the Rust ecosystem. IME breaking change releases more often than not require manual work anyway, and aren't *that* frequent so there's not that much value in it.

**Comment by marioortizmanero** [comment]
I've seen dependabot on quite a few libraries hosted on github. At the very least it serves as a notification to know a new breaking release is out. Otherwise I wouldn't know.

**Comment by jplatte** [comment]
Sure, though also I just realized that that release (which only contained another release bump I also made a PR for) might not have been sufficient motivation for 0.3.0 rather than another patch release anyway... https://github.com/sgodwincs/ordered-multimap-rs/pull/10#issuecomment-698380187

I'll update this issue again when that's resolved, for now please don't merge yet :sweat_smile:

**Comment by jplatte** [comment]
ordered-multipap isn't part of this crate's public API, right? If so, seems like it makes more sense to just use 0.3 and be done with it.

**Comment by zonyitoo** [comment]
So I can merge it this PR now?

**Comment by jplatte** [comment]
Yeah.

**Comment by jplatte** [comment]
Thanks! Will there be a 0.16.0 release (or even 0.15.4 with just this change) soon?

**Comment by zonyitoo** [comment]
Will definitely be released in 0.16.0. This is a breaking change for 0.15.x.

**Comment by jplatte** [comment]
I see. Is there an ETA for 0.16.0?

**Comment by zonyitoo** [comment]
Well, v0.16.0 is published already.

**Comment by jplatte** [comment]
Ah, nice! Thanks :)

**Pull request merged**
