### PR TITLE
use os special new line

### PR DESCRIPTION
**Pull request by woodgear**
use \r\n in windows

### CODE REVIEW

**Comment by zonyitoo** [comment]
I think this should be an option.

**Comment by woodgear** [comment]
where should i add this switch?could you give me some advise?

**Comment by zonyitoo** [comment]
```rust
struct WriteOption {
    policy: EscapePolicy,
    newline: NewLine,
}

enum NewLine {
    SystemDefault,
    CR,
    CRLF,
}

fn write_to_opt(..., opt: WriteOption)
```

For instance..

And then reimplement all the other `write_*` functions with `write_to_opt`.

**Comment by zonyitoo** [comment]
Closing it for lack of activities.

I am going to rewrite it with `WriteOption` on master.

**Pull request closed without merging**
