### PR TITLE
Simpler code structure, moved everything to `lib.rs`

### PR DESCRIPTION
**Pull request by marioortizmanero**
Accessing types like `Error` requires using `ini::ini::Error`, which is annoyingly repetitive. I think this library is much better off using top-level imports. I was going to just put `pub use ini::*` in `lib.rs` but I figured I could just move the code into `lib.rs` instead.

### CODE REVIEW

**Comment by zonyitoo** [comment]
This would become a breaking change, everyone that using `use ini::ini::Error` will get compliation failure.

**Comment by marioortizmanero** [comment]
I think it's a pretty easy to solve error and worth it for the future. The crate hasn't reached 1.0 yet so these breaking changes are expected.

**Comment by zonyitoo** [comment]
Hmm. I will accept it first.

**Comment by tshepang** [comment]
This should be bumped to v0.16.0 if it breaks code

**Comment by jplatte** [comment]
I think it's very uncommon to bump version before the release is actually made. Though I guess if you don't keep a change log (which I strongly encourage you to do) it's easier this way so you don't forget breaking changes since the last release.

Anyways, another (tiny) breaking change is incoming, so please don't release 0.16.0 yet :)

**Comment by zonyitoo** [comment]
https://github.com/zonyitoo/rust-ini/releases

Here is the change logs.

**Pull request merged**
